## Netlify configuration for deploying the Vite React client
[build]
  # Generate all product JSON artifacts (hashed products + productsByCategory) then build client
  command = "npm run generate:all && npm run build:client"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["razorpay", "mongodb"]

[dev]
  # Use existing combined Express + Vite dev server instead of rebuilding
  command = "npm run dev"
  targetPort = 5000       # The Express server (with Vite middleware) listens here
  port = 8888             # Netlify dev proxy port you open in browser
  functionsPort = 9999    # Separate port for function builder (auto-managed)
  autoLaunch = true

## Payment overrides must appear BEFORE generic /api proxy so they take precedence
[[redirects]]
  from = "/api/create-order"
  to = "/.netlify/functions/create-order"
  status = 200

[[redirects]]
  from = "/api/verify-payment"
  to = "/.netlify/functions/verify-payment"
  status = 200

## New serverless function overrides (must come before generic /api proxy)
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/products/slug/*"
  to = "/.netlify/functions/products-slug/:splat"
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products-list"
  status = 200
  force = true

[[redirects]]
  from = "/api/testimonials"
  to = "/.netlify/functions/testimonials"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/dashboard-data"
  to = "/.netlify/functions/admin-dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/products"
  to = "/.netlify/functions/admin-products"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/customers"
  to = "/.netlify/functions/admin-customers"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/settings"
  to = "/.netlify/functions/admin-settings"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/orders"
  to = "/.netlify/functions/admin-orders"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/orders/*/status"
  to = "/.netlify/functions/admin-order-status/:splat/status"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/login"
  to = "/.netlify/functions/admin-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/orders/track"
  to = "/.netlify/functions/orders-track"
  status = 200
  force = true

## Proxy API calls to Render backend (updated with deployed host) (after overrides)
[[redirects]]
  from = "/api/*"
  to = "https://choclatestore.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-From = "netlify-proxy" }

# Expose payment functions under /functions/payment/* optional nicer paths
[[redirects]]
  from = "/payment/create-order"
  to = "/.netlify/functions/create-order"
  status = 200

[[redirects]]
  from = "/payment/verify-payment"
  to = "/.netlify/functions/verify-payment"
  status = 200

[[redirects]]
  from = "/orders/history"
  to = "/.netlify/functions/order-history"
  status = 200

[[headers]]
  for = "/products.json"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=600"

[[headers]]
  for = "/products-manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=30"

[[headers]]
  for = "/products.*.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect all SPA routes to index.html (after API rule so API not swallowed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"
