## Netlify configuration for deploying the Vite React client
[build]
  # Generate static products.json then build client
  command = "npm run generate:products && npm run build:client"
  publish = "dist/public"

## Proxy API calls to Render backend (updated with deployed host)
[[redirects]]
  from = "/api/*"
  to = "https://choclatestore.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-From = "netlify-proxy" }

[[headers]]
  for = "/products.json"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=600"

[[headers]]
  for = "/products-manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=30"

[[headers]]
  for = "/products.*.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect all SPA routes to index.html (after API rule so API not swallowed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"
